apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pro
  name: pro
spec:
  tolerations:
    - key: "pro"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - image: prom/prometheus
    name: pro
    resources: {}
    volumeMounts:
       - name: prometheus
         mountPath: /etc/prometheus/
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
     - name: prometheus
       hostPath:
         path: /root/prometheus-k8s/prometheus
         type: Directory
status: {}
