apiVersion: v1
kind: Service
metadata:
  labels:
    run: pro
  name: pro
  namespace: default
spec:
  ports:
  -     port: 80
        protocol: TCP
        targetPort: 9090
  selector:
    run: pro
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
